# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    encrypt        = true
    key            = "security_stack/terraform.tfstate"
    region         = "us-east-1"
    bucket         = "menger-tf-state"
    dynamodb_table = "my-lock-table"
  }
}
